### ISSUE TITLE
ABBC3 FLOAT= & ALIGN= BBCODES issue

### ISSUE THREAD

**Issue by Galixte** [Sniper-E/tables#14]
Hi @Sniper-E,

When Tables extension is activated it adds some BBCodes like FLOAT= & ALIGN=. But if you use ABBC3 extension these have already been added.

See below:
- your extension code: https://github.com/Sniper-E/tables/blob/master/migrations/update_table.php#L121
```
			'align=' => array(
				'bbcode_match'		=> '[align={IDENTIFIER}]{TEXT}[/align]',
				'bbcode_tpl'		=> '<span style="text-align:{IDENTIFIER}; display:block;">{TEXT}</span>',
				'bbcode_helpline'	=> '',
				'display_on_posting'=> 1,
			),
			'float=' => array(
				'bbcode_match'		=> '[float={IDENTIFIER}]{TEXT}[/float]',
				'bbcode_tpl'		=> '<span style="float:{IDENTIFIER}">{TEXT}</span>',
				'bbcode_helpline'	=> '',
				'display_on_posting'=> 1,
```

- ABBC3 extension code: https://github.com/VSEphpbb/abbc3/blob/master/migrations/v310_m4_install_data.php#L56
```
		'align=center' => array(
			'bbcode_helpline'	=> 'ABBC3_ALIGN_HELPLINE',
			'bbcode_match'		=> '[align={IDENTIFIER}]{TEXT}[/align]',
			'bbcode_tpl'		=> '<span style="text-align:{IDENTIFIER}; display:block;">{TEXT}</span>',
		),
		'float=' => array(
			'bbcode_helpline'	=> 'ABBC3_FLOAT_HELPLINE',
			'bbcode_match'		=> '[float={IDENTIFIER}]{TEXT}[/float]',
			'bbcode_tpl'		=> '<div style="float:{IDENTIFIER}; padding:0 10px;">{TEXT}</div>',
```

As you can see the HTML replacement codes are not the same.

First problem, the Tables activation will overwrite the HTML replacement code from the ABBC3 with the HTML replacement code from Tables extension and it can be the cause of troubles on forums.

- My question is: Is it possible to check if these two bbocdes are already present in board the during activation of TABLES extension to avoid the issue of overwriting?

Second problem, last week i found this topic on phpBB.com: https://www.phpbb.com/community/viewtopic.php?f=556&t=2401271&p=14608076#p14608076, and the solution was to use this code for ALIGN= BBCode: https://www.phpbb.com/community/viewtopic.php?p=14716391#p14716391 or better code, in my opinion, with this ```<div style="text-align:{IDENTIFIER}">{TEXT}</div>```.

- So, my question: Would not it be useful to replace the currently code with this above?

**Comment by miri4ever** [comment]
Don't forget CENTER. I'm sure I deleted my center before since the new editor is using align. But as Galixte said it must be save to be checked if those commands already there. If not the sure must be added if used for tables.

**Comment by Galixte** [comment]
CENTER was removed one hour ago: https://github.com/Sniper-E/tables/pull/13/files#diff-df7b5de460c7aa1f3766fcad91ac3df3L115. ;)

**Comment by Sniper-E** [comment]
I removed center already in the pm I sent you guys.
Galixte removed center with his merge from the files I sent you.
I just removed align and float also which conflicted with abbc3.

**Comment by Galixte** [comment]
-----------------
I have removed this CENTER bbcode because it was in your files received by PM. It wasn’t my intention to do that, I am for that but i’m not the author from these modifications, i simply applied your modifications and added:

- Update with new guidelines displaying (your CSS/HTML/PHP/ENGLISH LANGUAGE changes),
- ADD BR after TABLE_GUIDELINES language key (to space the elements),
- remove blue color on lines in tables in ACP, see this: https://github.com/Sniper-E/tables/commit/646fa86c4e2239f37b899839d471b67ef0cb98ee#commitcomment-23429700,
- update FRENCH translation.

Source: https://github.com/Sniper-E/tables/pull/13 ;)

-----------

Moreoever, i’m happy about removing FLOAT and ALIGN bbcodes. Did you find a way to check when ABBC3 is installed, or you have simply removed these bbcodes?

**Comment by Sniper-E** [comment]
No I'm using a special migration file that VSE wrote for abbc3. Not sure
how to adjust it to look for a bbcode and not add it if it's there.
