### ISSUE TITLE
informations tables in ACP display blue lines

### ISSUE THREAD

**Issue by Galixte** [Sniper-E/tables#7]
Hi @Sniper-E,

since the 2.1.2 version, the information table in index page of administrator panel and on customize page (extension management page) are displayed with blue lines as separator.

I think you have added some css that cause this displaying problem. This line is at issue: https://github.com/Sniper-E/tables/blob/master/adm/style/acp_tables.css#L4.

See those examples:
![inked2017-08-02 04_12_05-parametres_li](https://user-images.githubusercontent.com/7478287/28855560-e84f1a42-773d-11e7-8740-eb20fbb491b9.jpg)
![inked2017-08-02 04_14_58-index de l administration - opera_li](https://user-images.githubusercontent.com/7478287/28855559-e84e199e-773d-11e7-93cb-5c8b6afdc307.jpg)

**Comment by Sniper-E** [comment]
Yes that was a little css I put in acp_tables.css to spruce up the acp tables a bit.
https://github.com/Galixte/tables/blob/master/adm/style/acp_tables.css#L4
Maybe ".table1 { background-color: #BBD7E8; }" would be a less abrasive change.
Not a good idea? Replace with ".table1 { }" would take that out. But I liked that addition.
I'll lighten that color up or take it out before 2.1.2 release if users don't like it.

**Comment by Galixte** [comment]
Remove this only in CSS admin and it will be good. ;)

**Comment by Galixte** [comment]
https://github.com/Sniper-E/tables/commit/646fa86c4e2239f37b899839d471b67ef0cb98ee#commitcomment-23429700
