### ISSUE TITLE
New permission doesn't appear in permission roles

### ISSUE THREAD

**Issue by Galixte** [Sniper-E/tables#8]
Hi @Sniper-E,

i don't see the new permission, where is it?

**Comment by Sniper-E** [comment]
ACP / Permissions / Group permissions / Select a group / Advanced Permissions / Post / Can use tables bbcode

**Comment by Galixte** [comment]
No, the permission doesn’t appear, i think there is a missing between 2.1.1 to 2.1.2 because i have update from 2.1.1 to 2.1.2.

**Comment by Galixte** [comment]
If i uninstall 2.1.2 version (updated from 2.1.1) by disabling extension, then deleting data, and if i re-activate extension, the permission appears.

So, i think there is a missing in migration from 2.1.1 to 2.1.2.

**Comment by Galixte** [comment]
@Sniper-E,

No, the permission doesn’t appear, i think there is a missing between 2.1.1 to 2.1.2 because i have update from 2.1.1 to 2.1.2.

If i uninstall 2.1.2 version (updated from 2.1.1) by disabling extension, then deleting data, and if i re-activate extension, the permission appears.

So, i think there is a missing in migration from 2.1.1 to 2.1.2.

**Comment by Sniper-E** [comment]
Looking into that problem. Testing we have noticed the perms are not really
working correctly.

I need to check the IF statement, templates and the migrations. There is a
problem somewhere.

You can set Administrator to No or Never and still see the button.
Testing...
